# UserSkeleton: contain a user id and 15 joints
uint8 userID
geometry_msgs/Vector3 head
geometry_msgs/Vector3 neck
geometry_msgs/Vector3 left_shoulder
geometry_msgs/Vector3 right_shoulder
geometry_msgs/Vector3 left_elbow
geometry_msgs/Vector3 right_elbow
geometry_msgs/Vector3 left_hand
geometry_msgs/Vector3 right_hand
geometry_msgs/Vector3 torso
geometry_msgs/Vector3 left_hip
geometry_msgs/Vector3 right_hip
geometry_msgs/Vector3 left_knee
geometry_msgs/Vector3 right_knee
geometry_msgs/Vector3 left_foot
geometry_msgs/Vector3 right_foot